spring.application.name=Cert_Gen_Backend
#server.port=8080

# Load blockchain configuration even when the 'fabric' profile is not explicitly activated.
spring.config.import=optional:classpath:application-fabric.yaml
#spring.profiles.active=default,application-fabric

# DB Configuration
spring.datasource.url=jdbc:postgresql://localhost:5000/Cert_Generator
spring.datasource.username=postgres
spring.datasource.password=nilesh#123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# JWT Configuration
SECRET_KEY=MzJieXRlc0tleVNlY3JldEtleVNlY3JldEtleVNlY3JldA==
EXPIRATION=1


#Mail service configuration

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sequelextreme@gmail.com
spring.mail.password=rgdtzchxdrvkytio
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Certificate Storage Paths

certificate.storage.pdf.path=E:/DRDO PROJECT FINAL/Backend/ServerStorage/certificates

VERIFICATION_BASE_URL=http://localhost:8080/api/verification/verify/



# Director Keystore Configuration with root certificate
director.keystore.path=E:/DRDO PROJECT FINAL/Backend/ServerStorage/rootca/director-keystore.p12
director.keystore.password=Nilesh#123
director.keystore.alias=director




ROOT_CA_CERT_PATH=E:/DRDO PROJECT FINAL/Backend/ServerStorage/rootca/drdo-root-ca.pem

